config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  resources :articles
  resources :shared_links

  get '/about' => 'welcome#about'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/shared_link.rb
class SharedLink < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_url
  end

  def edit
    @article = Article.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_url
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to articles_url
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/controllers/shared_links_controller.rb
class SharedLinksController < ApplicationController
  def new
    @link = SharedLink.new
  end

  def edit
    @link = SharedLink.find(params[:id])
  end

  def create
    @link = SharedLink.new(link_params)
    unless @link.link.include?'http'
      tmp = 'http://' + @link.link
      @link.link = tmp
    end
    @link.save
    redirect_to root_url
  end

  def link_params
    params.require(:shared_link).permit(:name, :link)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @articles = Article.page(params[:page]).per(10)
    @shared_links = SharedLink.all
  end

  def about

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''
    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/shared_links_helper.rb
module SharedLinksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/create.html.erb
<h1>Article#create</h1>
<p>Find me in app/views/article/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Article#destroy</h1>
<p>Find me in app/views/article/destroy.html.erb</p>

app/views/articles/edit.html.erb
<div class="row">
  <div class="col-sm-8">
    <%= form_for @article, url: articles_path do |f| %>
        <div class="form_content">
          <%= f.label :title, "文章标题" %>
          <%= f.text_field :title, class: "form-control" %>

          <%= f.label :content, "文章内容" %>
          <%= f.text_area :content, class: "form-control", style: "resize:none;", rows: 10 %>
        </div>
        <%= f.submit "提交", class: "btn btn-primary" %>
    <% end %>
  </div>
  <div class="col-sm-4">
  </div>
</div>

app/views/articles/index.html.erb
<div class="row">
  <div class="col-sm-8">
    <table class="table">
      <caption>
        <div class="row">
          <div class="col-sm-6" align="left">文章列表</div>
          <% if current_user %>
            <div class="col-sm-6" align="right"><%= link_to '新博客', new_article_path %></div>
          <% end %>
        </div>
      </caption>
      <tbody>
      <% @articles.each do |article| %>
          <tr>
            <td><%= link_to article.title, article_path(article) %></td>
            <td><%= link_to '编辑', edit_article_path(article) %></td>
            <td><%= link_to '删除', article_path(article), method: :delete %></td>
            <td><%= article.created_at.to_s(:db) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-sm-4">

  </div>
</div>

app/views/articles/new.html.erb
<div class="row">
  <div class="col-sm-8">
    <%= form_for @article, url: articles_path do |f| %>
        <div class="form_content">
          <%= f.label :title, "文章标题" %>
          <%= f.text_field :title, class: "form-control" %>

          <%= f.label :content, "文章内容" %>
          <%= f.text_area :content, class: "form-control", style: "resize:none;", rows: 10 %>
        </div>
        <%= f.submit "提交", class: "btn btn-primary" %>
    <% end %>
  </div>
  <div class="col-sm-4">
  </div>
</div>

app/views/articles/show.html.erb
<h1>Article#show</h1>
<p>Find me in app/views/article/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>孙庆鹏的Blog</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Blog', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= nav_link '文章列表', articles_path %></li>
        <li><%= nav_link '关于我', about_path %></li>
        <% if current_user %>
            <li><%= link_to('退出', destroy_user_session_path, :method => :delete) %></li>
            <li><%= link_to('修改密码', edit_registration_path(:user)) %></li>
        <% else %>
            <li><%= link_to('登录', new_session_path(:user)) %></li>
        <% end %>
      </ul>
    </div>

  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/shared_links/edit.html.erb
<h1>SharedLink#edit</h1>
<p>Find me in app/views/shared_link/edit.html.erb</p>

app/views/shared_links/new.html.erb
<div class="row">
  <div class="col-sm-8">
    <%= form_for @link, url: shared_links_path do |f| %>
        <div class="form_content">
          <%= f.label :name, "链接名称" %>
          <%= f.text_field :name, class: "form-control" %>

          <%= f.label :link, "链接地址" %>
          <%= f.text_area :link, class: "form-control", style: "resize:none;", rows: 10 %>
        </div>
        <%= f.submit "提交", class: "btn btn-primary" %>
    <% end %>
  </div>
  <div class="col-sm-4">
  </div>
</div>

app/views/welcome/about.html.erb
<div class="row">
<div class="col-sm-8">
  <p>一个永远进步的程序员，想努力成为设计师.</p>
  <p>Email：sunqingpeng@hotmail.com</p>
  <p>Tel: 18640244301 </p>
</div>
<div class="col-sm-4">
</div>
</div>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-sm-8">
    <% @articles.each do |article|  %>
        <div class="article_content">
          <h3><%= link_to article.title, article_path(article) %></h3>
          <p><%= article.content %></p>
        </div>
    <% end %>
    <%= paginate @articles %>
  </div>

  <div class="col-sm-4">
    <div class="right_side">
      <h3>有用链接</h3>
      <% @shared_links.each do |shared_link| %>
        <p><%= link_to(shared_link.name, shared_link.link) %></p>
      <% end %>
    </div>
  </div>
</div>